### ISSUE TITLE
turquoise section breaks on mobile

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#160]
![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/7155640/34879277-ab5d8d9a-f77a-11e7-8ee5-d80e190c8a16.jpg)

**Comment by s-kennedy** [comment]
Addressed in PR #161

**Comment by s-kennedy** [comment]
@dirkcuys can you close this issue please? (or change my permissions so i can close it?)

**Comment by GrifP** [comment]
@Dirk can you update sharon's permissions?
