### ISSUE TITLE
Automate story updates in navbar

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#200]
Decide on solution so that Nico doesnt have to manually update blogposts in the header

**Comment by dirkcuys** [comment]
@GrifP - last week during the tech call we discussed that this may not be needed since we want to update the topnav and that the update won't include links to the latest stories. If so, should we close this issue and add a new issue for updating the topnav?

**Comment by GrifP** [comment]
@dirkcuys yes, I agree.
