### ISSUE TITLE
titles not displaying on learning circle page

### ISSUE THREAD

**Issue by nicop2pu** [p2pu/p2pu-website#224]
https://www.p2pu.org/en/learning-circles/

**Comment by dirkcuys** [comment]
@s-kennedy is this related to the new search cards?

**Comment by dirkcuys** [comment]
Turns out the titles we there, but in white. Turned them black again, but I suspect the actual issue is that the backgrounds are supposed to not be white.

**Comment by GrifP** [comment]
Yes, it looks like the background colors have disappeared from the LC cards.

@dirkcuys -  changing the text grey also affected the /courses page, which still has the color in the background, but now looks bad with the grey text over it.
