### ISSUE TITLE
Meeting days checkbox on learning circles page doesn't remove days

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-website#238]
![image](https://user-images.githubusercontent.com/121995/46537430-920ea500-c8b1-11e8-9a6f-fd55d162e147.png)

**Comment by s-kennedy** [comment]
This was fixed in https://github.com/p2pu/p2pu-search-cards/commit/003389b8edf8f68815f935d06d0c469de8d3332e#diff-55c72cff10df5da2663a14db2837a340

It's working properly on the master branch of p2pu-website, I think it just needs to be deployed.
