### ISSUE TITLE
Add Courses and Topics category on /facilitate to reflect new Discourse category

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#253]
https://community.p2pu.org/c/learning-circles/courses-and-topics

**Comment by s-kennedy** [comment]
@GrifP what intro text do you want to use for this section? For now I took the text from the pinned post, do you want to edit it? Also can you tag the featured threads?

![screen shot 2019-02-11 at 5 54 10 pm](https://user-images.githubusercontent.com/10519011/52599463-a72eae00-2e26-11e9-9ec2-5a746222a839.png)

**Comment by GrifP** [comment]
just added some featured. the text you put is great.

**Comment by s-kennedy** [comment]
Fixed in #257
