### ISSUE TITLE
Add EU Erasmus+ grant logo to funding section on landing page

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-website#268]
[ref](https://www.google.com/search?q=EU+Erasmus%2B&rlz=1C5CHFA_enUS726US727&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjB1L7P8IbgAhXom-AKHStGBisQ_AUIDygC&biw=1333&bih=767&dpr=2#imgrc=HG7_hDaiglFWGM:)

**Comment by s-kennedy** [comment]
Fixed in #272
