### ISSUE TITLE
update partner list

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#269]
LA, Onondaga...

**Comment by GrifP** [comment]
Mid-Continent Public Library https://www.mymcpl.org/
Onondaga Free Library https://oflibrary.org/
Los Angeles Public Library https://www.lapl.org/
Information Society Development Foundation http://frsi.org.pl/en/
Progress Foundation http://www.progressfoundation.ro/en/
Cologne Public Library https://www.stadt-koeln.de/leben-in-koeln/stadtbibliothek/
Finnish eLearning Centre https://eoppimiskeskus.fi/en/
West Vancouver Memorial Library https://westvanlibrary.ca/
Dokk1 https://dokk1.dk/english

**Comment by GrifP** [comment]
It looks like this and the other change to Ryan's name weren't merged... @s-kennedy was there a pull request?

**Comment by s-kennedy** [comment]
Yes, there's a PR up now that includes these changes.

**Comment by s-kennedy** [comment]
Fixed in #272
