### ISSUE TITLE
Update site metadata

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#327]
- [x] Change "Taking online courses together for free in libraries" to "Learning by the people, for the 
people"
- [ ] Change "Learning Circles" to "Peer 2 Peer University"  on https://learningcircles.p2pu.org/en/
- [x] Change favicon to this image:
![](https://thumbs.gfycat.com/ClutteredGivingGonolek-small.gif)

## Comments start here

Streamline favicons:

landing page = pixelated orange
discourse = all four

personally I think the turquoise looks the sharpest, but open to other ideas as well!

![Screen Shot 2020-04-29 at 4 17 34 PM](https://user-images.githubusercontent.com/7155640/80748420-e3fdc800-8af2-11ea-9e14-f66b10b772ec.png)

**Comment by GrifP** [comment]
landing page = pixelated orange
discourse = all four

personally I think the turquoise looks the sharpest, but open to other ideas as well!

**Comment by GrifP** [comment]
Change "Learning Circles" to "Peer 2 Peer University"
Change "Taking online courses together for free in libraries" to "Learning by the people, for the people"

<img width="393" alt="Screen Shot 2020-06-15 at 4 18 03 PM" src="https://user-images.githubusercontent.com/7155640/84701988-f194d300-af23-11ea-8a21-49e8609792f3.png">

**Comment by GrifP** [comment]
@beckymargraf any thoughts on any of this?

**Comment by beckymargraf** [comment]
My preference is the P2PU stacked logo since it feels the most recognizable.

**Comment by beckymargraf** [comment]
Agreed on changing "Learning Circles" to Peer 2 Peer University. 

For the secondary text, I think we should have a blurb that's a little more explicit about who we are/what we do. (I'd like to use it in other places like our Twitter bio too.) I'll take a whack at it and share at comms!

**Comment by GrifP** [comment]
Sounds great! Thanks.

**Comment by dirkcuys** [comment]
@GrifP I've update the description for p2pu.org, for future reference, you can make the change [here](https://github.com/p2pu/p2pu-website/blob/master/_config.yml#L4)

> Change "Learning Circles" to "Peer 2 Peer University"

Is this on learningcircles.p2pu.org or on www.p2pu.org?

Could you please update the description of the issue with a link to the favicon we should use?

**Comment by beckymargraf** [comment]
@dirkcuys Grif and I met to finalize the web description last week. I just submitted a pull request with the updated desc!

**Comment by dirkcuys** [comment]
Thanks @beckymargraf - could you please also edit the opening comment to link to the correct favicon. Unless you agree that this should be the favicon, in which case I'd happily oblige :)  ![](https://camo.githubusercontent.com/37bdc7e8627412c0e427e75eadd9901e14b7f47c/68747470733a2f2f7468756d62732e6766796361742e636f6d2f436c75747465726564476976696e67476f6e6f6c656b2d736d616c6c2e676966)

**Comment by beckymargraf** [comment]
@dirkcuys Yeah, is the existing 32x32 one okay or do you need a diff size/format?

![32x32](https://community.p2pu.org/uploads/default/optimized/2X/9/94d516b4d62243770ddb8fe24118cd313c5e1a2c_2_32x32.png)

**Comment by dirkcuys** [comment]
Thanks, that's fine.

Could you please think how we can improve https://github.com/p2pu/design to indicate what assets are suitable for the web - I'm unlikely to notice next time I pull a logo from there, esp since my display tends to be red-shifted

**Comment by GrifP** [comment]
Wait I actually really want this shirt
<https://github.com/p2pu/design/blob/master/T-Shirt/P2PU-shirt-class-2009.svg>
from
2009
[image: image.png]
