### ISSUE TITLE
Fix or remove old URLs

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-website#369]
These pages look like they should be removed
- https://www.p2pu.org/en/menu/
- https://www.p2pu.org/en/publications/blog/
- https://www.p2pu.org/en/publications/reports/
- https://www.p2pu.org/en/publications/roundtables/
- https://www.p2pu.org/en/publications/talks/

**Comment by dirkcuys** [comment]
@beckymargraf not sure /talks/ and /roundtables/ have any useful info, but I think they are examples of thinking about integrating other resources in the site

**Comment by beckymargraf** [comment]
I like the visuals on /talks! How are these entries added to the list?

I'm not able to load any content on /roundtables, just the spinning gear. What should it look like or what type of content should be there?

**Comment by dirkcuys** [comment]
Talks pull data from [_data/presentations.yml](https://github.com/p2pu/p2pu-website/blob/master/_data/presentations.yml)

Roundtables are missing a library to load - it used to display [this youtube playlist](https://www.youtube.com/playlist?list=PLtywLmgP0F55FHsO3n93YLw_sGLzp9-5X) styled differently
