### ISSUE TITLE
Finalize links in footer

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-website#437]
![image](https://user-images.githubusercontent.com/121995/136364258-2084c985-362e-4092-8068-375c8d0cc22d.png)

This is the current list:

- Learning Circles
  -    Find a Learning Circle
  -    Host a Learning Circle
  -    Course Library Handbook
  -    Organize a Team
- Facilitator Resources
  -    Facilitator Handbook
  -    Create a Learning Circle
- About P2PU
  -    About
  -    Blog
  -    Hire Us
  -    Jobs
  -    Donate
  -    Contact
- Community
  -    Forum
  -    Events
- Membership
  -    Sign Up
  -    Log In
  -    Institutional Partners
- Need Help?
  -    Contact Support
  -    support@p2pu.org
- Terms of Service
- Privacy Policy

This should be trimmed a bit and clarified as currently there are items that would have the same link with a different heading/label like "Host a Learning Circle" and "Create a Learning Circle".

**Comment by dirkcuys** [comment]
@GrifP @beckymargraf what are your thoughts. match the links with the nav structure in the header, only put the privacy and terms or slim down the current list?

**Comment by dirkcuys** [comment]
Another question, where should "Facilitate a Learning Circle" link?

**Comment by beckymargraf** [comment]
Sorry Dirk, should have mentioned before but we need to add "Site Image Credits" here too. Maybe first thing in the section with TOS and Privacy Policy? 

Link here: https://handbook.p2pu.org/tools-and-resources/marketing-materials/p2pu.org-image-credits
