### ISSUE TITLE
facilitate page menu

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#62]
From the facilitate page, some of the menu styling isn't showing up - P2PU appears as non-hyperlink plain text (rather than the logo), there is no hamburger icon next to menu, and no X shows up to close the menu

<img width="1352" alt="screen shot 2017-07-03 at 3 35 59 pm" src="https://user-images.githubusercontent.com/7155640/27805918-71698218-6005-11e7-9e4f-05467e059e0e.png">

**Comment by dirkcuys** [comment]
@GrifP please confirm if this is still the case, this is what I see on /facilitate:

![firefox_screenshot_2017-07-06t10-14-36 031z](https://user-images.githubusercontent.com/121995/27906658-c83c16aa-6244-11e7-971d-eb06a6250b82.png)

**Comment by GrifP** [comment]
i dont see this as an issue anymore, so I'll close this.
