### ISSUE TITLE
change wrench icon on facilitate

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#74]
I changed the text here, so a wrench doesn't make much sense any more. How about a rocket ship? Is that trite?

**Comment by s-kennedy** [comment]
Unfortunately google's icon collection doesn't have a rocket ship.. a plane taking off is the closest one I could find, but I also found some alternatives (see below). I think the map marker kind of fits well with the idea of localizing the learning circles model.

https://material.io/icons/

flight takeoff
room (map marker)
show chart
game pad (kind of looks like arrows coming together)

**Comment by GrifP** [comment]
agreed
