### ISSUE TITLE
Consolidate CSS files

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-website#91]
Currently there are 3 CSS files combining some parts of the SASS framework:

1. [p2pu-custom.scss](https://github.com/p2pu/p2pu-website/blob/gh-pages/assets/css/p2pu-custom.scss)
1. [p2pu-facilitate.scss](https://github.com/p2pu/p2pu-website/blob/gh-pages/assets/css/p2pu-facilitate.scss)
1. [p2pu-index.scss](https://github.com/p2pu/p2pu-website/blob/gh-pages/assets/css/p2pu-index.scss)

These files should be consolidated

**Comment by s-kennedy** [comment]
@dirkcuys can I close this issue? We still have all three of these CSS files but now they're all importing the p2pu-theme base css file and a few page-specific files.
