### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by GrifP** [p2pu/p2pu-website#94]
p2pu logo in info.p2pu.org is broken

'work with us' on homepage goes to /en/collaborate (which isn't a page)...needs to be updated to /en/workwithus

**Comment by dirkcuys** [comment]
Both issues should be resolved now

**Comment by GrifP** [comment]
The logo is, but 'work with us' on homepage still redirects to /collaborate, which is not a real page.

**Comment by dirkcuys** [comment]
@GrifP please confirm if the issue is resolved now

**Comment by GrifP** [comment]
confirmed
