### ISSUE TITLE
Blog search bar placement is over content

### ISSUE THREAD

**Issue by kitsandkats** [p2pu/p2pu-website#96]
The "Search" bar on a blog post page is placed weirdly on the page (see screenshot) and the "Show all posts" link is displaying under the main nav bar. 
(I am using Chrome Version 59.0.3071.115 (Official Build) (64-bit))

<img width="1109" alt="screen shot 2017-07-24 at 11 42 45 am" src="https://user-images.githubusercontent.com/6548760/28531613-5c8f1b08-7065-11e7-92b2-02f403533560.png">

**Comment by dirkcuys** [comment]
@kitsandkats - thanks. The search bar is now updated to be static rather than use affix. Right now we're reconsidering if we want to keep using Wordpress or if we want to switch to medium or another platform?
